// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCVBBi6nUjXz-PXz_M8jNp0p4evCRYh_E',
    appId: '1:440745273162:web:dabaf0d544d3aa2d6dc3b3',
    messagingSenderId: '440745273162',
    projectId: 'dispensadorpastillas2026',
    authDomain: 'dispensadorpastillas2026.firebaseapp.com',
    storageBucket: 'dispensadorpastillas2026.firebasestorage.app',
    measurementId: 'G-1GZL1QVP3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSB-HMStbQfDgdeiTY-QTfvFbO1dSDoIA',
    appId: '1:440745273162:android:705bc58c95de432e6dc3b3',
    messagingSenderId: '440745273162',
    projectId: 'dispensadorpastillas2026',
    storageBucket: 'dispensadorpastillas2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCGGqK9w5pSF43HM3wIymRln5cKcmN8c',
    appId: '1:440745273162:ios:a910a02b97a581476dc3b3',
    messagingSenderId: '440745273162',
    projectId: 'dispensadorpastillas2026',
    storageBucket: 'dispensadorpastillas2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCGGqK9w5pSF43HM3wIymRln5cKcmN8c',
    appId: '1:440745273162:ios:a910a02b97a581476dc3b3',
    messagingSenderId: '440745273162',
    projectId: 'dispensadorpastillas2026',
    storageBucket: 'dispensadorpastillas2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCVBBi6nUjXz-PXz_M8jNp0p4evCRYh_E',
    appId: '1:440745273162:web:b144ddd60f6127eb6dc3b3',
    messagingSenderId: '440745273162',
    projectId: 'dispensadorpastillas2026',
    authDomain: 'dispensadorpastillas2026.firebaseapp.com',
    storageBucket: 'dispensadorpastillas2026.firebasestorage.app',
    measurementId: 'G-M58TGX53LR',
  );
}
